# 性格のクラスタリングで使用するデータを抽出してCSV出力する

In [9]:
import pandas as pd

In [10]:
# 数値に変換した回答結果から性格のクラスタリングに使用する部分のみを抽出
df_csv = pd.read_csv('/home/res/converted/answers_int.csv', usecols=list(range(19, 25)))

In [11]:
df_csv

,通常，自分から話を始めることはない,どちらかというと控えめで，静かな性格である,深く考えるより，すぐに行動したい,リーダーとして皆を引っ張っていきたい,近くでイベントがあれば参加するほうだ,どちらかというと，開放的で，陽気なタイプだと思う
0,1,2,4,2,3,3
1,2,4,2,3,1,0
2,3,4,3,0,3,3
3,4,4,2,0,2,2
4,4,2,5,0,0,3
5,1,3,2,3,3,2
6,4,5,3,0,3,0
7,2,1,4,1,1,0
8,5,4,5,1,4,0
9,2,4,3,1,3,4
10,3,5,3,0,1,1
11,2,0,5,2,0,0
12,2,4,2,4,2,3
13,3,3,4,2,3,0
14,1,1,3,5,4,3
15,5,4,5,3,3,1
16,1,1,5,1,5,4
17,3,4,1,0,2,1
18,2,3,3,2,3,2
19,3,4,4,5,2,1
20,4,3,5,3,3,1
21,1,4,1,3,1,1
22,2,4,2,3,4,3
23,3,4,2,2,2,2
24,1,2,1,1,4,3
25,4,2,2,1,3,2
26,5,4,5,0,2,2
27,3,4,2,1,1,2
28,2,0,3,5,1,2
29,1,0,3,2,2,4
30,2,3,4,0,2,3
31,1,0,4,1,1,4
32,5,5,3,0,1,0
33,3,2,4,2,2,4
34,4,4,4,3,3,0
35,0,1,4,4,3,3
36,0,2,0,0,3,2
37,0,5,3,0,3,0
38,2,4,1,3,3,2
39,3,3,2,1,1,2
40,2,3,4,3,3,2
41,2,4,4,4,3,3

In [12]:
# CSV出力
df_csv.to_csv('/home/res/datasets/human_data.csv', index=False)