# 静的なレコメンドNN用の学習データセットを作成

# import

In [1]:
import numpy as np
import pandas as pd

# CSV読み込み

In [2]:
# 数値に変換した回答結果から必要なデータを抽出
df_csv = pd.read_csv('/home/res/converted/answers_int.csv', usecols=list(range(3, 15)))

In [3]:
df_csv.head()

,あなたは普段，どのような遊びをよくされていますか？次のジャンルのうち，最も当てはまるものを1つ選択してください(必須)．,あなたは普段，どのような遊びをよくされていますか？次のジャンルのうち，2番目に当てはまるものを1つ選択してください(任意)．,あなたは普段，どのような遊びをよくされていますか？次のジャンルのうち，3番目に当てはまるものを1つ選択してください(任意)．,その他，普段よく遊ばれるジャンルがあれば，当てはまるものを複数選択してください．,上記で選択した遊び(普段よくする遊び)を行うときは，1日でお金を平均で幾らほど使われますか？,上記で選択した遊び(普段よくする遊び)を行うときは，自然に囲まれた中で遊びたい気分のときが多いですか？それとも街や駅前に出て遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，エキサイティングな遊びをしたい気分のときが多いですか？それとも，ゆったりのんびり遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，遠出したい気分のときが多いですか？それとも近場で遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，色々な場所を転々としたい気分のときが多いですか？それとも1か所にとどまって遊びたい気分の時が多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，室内で遊びたい気分のときが多いですか？それとも室外で遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，何人の友達と遊びに行くことが多いですか？平均してお答えください．,上記で選択した遊び(普段よくする遊び)を行うときは，人(友達など)とどのくらい会話をしますか？（%の値は～したいという気持ちの度合いです）
0,1,3,0,"[0, 1, 3, 5, 6]",3,3,2,3,4,3,2,4
1,7,3,6,[5],3,1,1,3,3,4,1,3
2,6,5,2,"[2, 5, 6]",5,3,3,1,4,5,1,5
3,3,6,4,"[1, 5, 7]",1,2,2,3,3,3,1,3
4,1,0,3,[8],1,4,2,2,3,3,1,4

# 入力データと正解ラベルに分割

In [4]:
# 入力データ
df_input = df_csv.iloc[:, 4:]

In [5]:
df_input.head()

,上記で選択した遊び(普段よくする遊び)を行うときは，1日でお金を平均で幾らほど使われますか？,上記で選択した遊び(普段よくする遊び)を行うときは，自然に囲まれた中で遊びたい気分のときが多いですか？それとも街や駅前に出て遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，エキサイティングな遊びをしたい気分のときが多いですか？それとも，ゆったりのんびり遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，遠出したい気分のときが多いですか？それとも近場で遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，色々な場所を転々としたい気分のときが多いですか？それとも1か所にとどまって遊びたい気分の時が多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，室内で遊びたい気分のときが多いですか？それとも室外で遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，何人の友達と遊びに行くことが多いですか？平均してお答えください．,上記で選択した遊び(普段よくする遊び)を行うときは，人(友達など)とどのくらい会話をしますか？（%の値は～したいという気持ちの度合いです）
0,3,3,2,3,4,3,2,4
1,3,1,1,3,3,4,1,3
2,5,3,3,1,4,5,1,5
3,1,2,2,3,3,3,1,3
4,1,4,2,2,3,3,1,4

In [6]:
# ジャンル一覧を読み込み
df_genre = pd.read_csv('/home/res/converted/genre_list.csv')

df_genre

   no                             genre
0   0  アウトドア（マリンスポーツ・釣り・BBQ・登山・ハイキングなど）
1   1       エンタメ（ボウリング場・カラオケ・ゲームセンターなど）
2   2   スポーツ（ボルダリング・ゴルフ・サイクリング・ジム・ヨガなど）
3   3           観光（観光名所巡り・日帰り温泉・食べ歩きなど）
4   4                  遊園地・動物園・水族館・海水浴場
5   5               友達との飲み会（外飲み・飲み歩きなど）
6   6                  外での買い物（アウトレットなど）
7   7   ショー・展示・催し（映画館・ミュージカル・博物館・美術館など）
8   8                                なし

In [7]:
# 正解ラベル
df_label = df_csv.iloc[:, :4]

In [8]:
df_label.head()

,あなたは普段，どのような遊びをよくされていますか？次のジャンルのうち，最も当てはまるものを1つ選択してください(必須)．,あなたは普段，どのような遊びをよくされていますか？次のジャンルのうち，2番目に当てはまるものを1つ選択してください(任意)．,あなたは普段，どのような遊びをよくされていますか？次のジャンルのうち，3番目に当てはまるものを1つ選択してください(任意)．,その他，普段よく遊ばれるジャンルがあれば，当てはまるものを複数選択してください．
0,1,3,0,"[0, 1, 3, 5, 6]"
1,7,3,6,[5]
2,6,5,2,"[2, 5, 6]"
3,3,6,4,"[1, 5, 7]"
4,1,0,3,[8]

# バイナリパターンの学習データセットを作成

In [9]:
df_train_bin = df_label.iloc[:, :3]

In [10]:
df_train_bin.head()

,あなたは普段，どのような遊びをよくされていますか？次のジャンルのうち，最も当てはまるものを1つ選択してください(必須)．,あなたは普段，どのような遊びをよくされていますか？次のジャンルのうち，2番目に当てはまるものを1つ選択してください(任意)．,あなたは普段，どのような遊びをよくされていますか？次のジャンルのうち，3番目に当てはまるものを1つ選択してください(任意)．
0,1,3,0
1,7,3,6
2,6,5,2
3,3,6,4
4,1,0,3

In [13]:
def map_2vec(row):
    vector = np.zeros(len(df_genre) - 1).astype(np.int64)
    for x in row:
        if x != 8:
            vector[x] = 1
    return vector / sum(vector)

df_train_bin.apply(map_2vec, axis=1)

array([0.33333333, 0.33333333, 0.        , 0.33333333, 0.        ,
       0.        , 0.        , 0.        ])

In [12]:
# CSV出力
df_csv_bin = df_input.copy()
df_csv_bin['label'] = df_train_bin.apply(map_2vec, axis=1)
df_csv_bin.to_csv('/home/res/datasets/static-info_data_bin.csv', index=False)

df_csv_bin

,上記で選択した遊び(普段よくする遊び)を行うときは，1日でお金を平均で幾らほど使われますか？,上記で選択した遊び(普段よくする遊び)を行うときは，自然に囲まれた中で遊びたい気分のときが多いですか？それとも街や駅前に出て遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，エキサイティングな遊びをしたい気分のときが多いですか？それとも，ゆったりのんびり遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，遠出したい気分のときが多いですか？それとも近場で遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，色々な場所を転々としたい気分のときが多いですか？それとも1か所にとどまって遊びたい気分の時が多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，室内で遊びたい気分のときが多いですか？それとも室外で遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，何人の友達と遊びに行くことが多いですか？平均してお答えください．,上記で選択した遊び(普段よくする遊び)を行うときは，人(友達など)とどのくらい会話をしますか？（%の値は～したいという気持ちの度合いです）,label
0,3,3,2,3,4,3,2,4,"[1, 1, 0, 1, 0, 0, 0, 0]"
1,3,1,1,3,3,4,1,3,"[0, 0, 0, 1, 0, 0, 1, 1]"
2,5,3,3,1,4,5,1,5,"[0, 0, 1, 0, 0, 1, 1, 0]"
3,1,2,2,3,3,3,1,3,"[0, 0, 0, 1, 1, 0, 1, 0]"
4,1,4,2,2,3,3,1,4,"[1, 1, 0, 1, 0, 0, 0, 0]"
5,1,3,3,2,3,3,1,3,"[0, 0, 0, 1, 0, 1, 1, 0]"
6,0,3,2,2,5,1,0,3,"[0, 1, 1, 0, 0, 0, 1, 0]"
7,0,3,1,1,1,1,2,3,"[0, 0, 0, 0, 0, 1, 0, 0]"
8,3,4,5,3,4,1,1,3,"[0, 0, 0, 0, 0, 1, 0, 1]"
9,5,3,3,4,4,4,3,5,"[0, 1, 0, 1, 0, 1, 0, 0]"
10,1,3,1,0,1,0,3,3,"[1, 1, 0, 0, 0, 1, 0, 0]"
11,3,4,5,5,3,4,5,5,"[0, 0, 0, 1, 0, 1, 1, 0]"
12,2,3,2,1,2,1,1,2,"[0, 1, 0, 0, 0, 1, 0, 1]"
13,1,4,2,1,2,1,3,4,"[0, 1, 1, 0, 0, 1, 0, 0]"
14,2,4,4,3,4,1,1,3,"[0, 1, 0, 0, 0, 0, 1, 1]"
15,1,2,4,2,3,3,0,0,"[0, 1, 1, 0, 0, 0, 0, 1]"
16,1,1,4,2,2,4,2,4,"[1, 0, 1, 1, 0, 0, 0, 0]"
17,0,3,1,1,4,4,1,3,"[0, 1, 0, 0, 0, 0, 1, 1]"
18,1,3,3,3,3,2,2,3,"[0, 0, 0, 1, 0, 1, 0, 1]"
19,2,3,2,2,4,2,3,4,"[0, 0, 1, 1, 0, 1, 0, 0]"
20,0,4,4,3,2,1,0,0,"[0, 0, 0, 1, 0, 0, 0, 1]"
21,1,4,3,2,3,3,1,4,"[0, 0, 0, 1, 0, 1, 1, 0]"
22,0,3,2,2,4,2,0,0,"[0, 0, 0, 0, 0, 0, 1, 0]"
23,1,2,2,2,3,2,0,0,"[0, 1, 0, 1, 0, 0, 1, 0]"
24,2,2,4,4,3,4,1,4,"[0, 0, 1, 1, 0, 1, 0, 0]"
25,3,4,2,2,2,2,0,3,"[0, 1, 0, 0, 0, 1, 0, 1]"
26,1,1,5,4,2,2,2,4,"[1, 1, 0, 0, 0, 1, 0, 0]"
27,2,1,1,3,3,4,1,4,"[0, 0, 0, 1, 1, 0, 1, 0]"
28,3,3,3,4,3,3,2,3,"[0, 1, 0, 1, 0, 1, 0, 0]"
29,3,3,2,1,4,2,1,5,"[0, 0, 1, 0, 0, 1, 1, 0]"
30,2,2,1,2,2,2,1,3,"[0, 0, 0, 0, 0, 1, 0, 1]"
31,1,4,2,1,2,1,1,3,"[0, 0, 0, 0, 0, 1, 1, 1]"
32,1,2,0,1,1,0,5,3,"[0, 0, 0, 0, 0, 1, 0, 0]"
33,3,3,4,4,3,4,1,4,"[0, 1, 0, 1, 0, 1, 0, 0]"
34,2,3,2,2,3,2,2,2,"[0, 1, 1, 0, 0, 0, 1, 0]"
35,3,2,4,4,5,5,1,4,"[0, 0, 1, 0, 1, 0, 1, 0]"
36,1,1,2,3,1,2,1,3,"[0, 1, 0, 1, 0, 0, 1, 0]"
37,1,0,5,2,3,5,1,5,"[1, 0, 0, 0, 0, 0, 0, 0]"
38,3,3,2,2,4,1,3,4,"[0, 1, 1, 0, 0, 1, 0, 0]"
39,0,2,1,3,3,3,2,3,"[0, 0, 0, 1, 1, 0, 1, 0]"
40,1,2,3,2,2,3,5,3,"[0, 1, 1, 0, 0, 1, 0, 0]"
41,0,2,1,2,4,3,0,2,"[0, 0, 1, 1, 0, 0, 0, 1]"

# 重みパターンの学習データセットを作成

In [14]:
# セル内のリストが文字列になっているのでリストに変換
def map_stol(x):
    lst = x.replace('[', '').replace(']', '').split(',')
    return [int(v) for v in lst]

df_label.iloc[:, 3] = df_label.iloc[:, 3].map(map_stol)

In [15]:
def apply_rm_duplicate(row):
    for i in range(3):
        # 途中でリストが空になったらNoneを返す
        if not row[3]:
            return None
        # 第1~3希望で選んだジャンルがリストに含まれていたら削除
        if row[i] in row[3]:
            row[3] = row[3].remove(row[i])
    
    # リストが空or"なし"のみの場合Noneを返す
    if not row[3] or (len(row[3]) == 1 and row[3][0] == 8):
        return None
    
    return row[3]
            
df_label.iloc[:, 3] = df_label.apply(apply_rm_duplicate, axis=1)

In [16]:
# なしをNoneに変換
df_label.iloc[:, 1] = df_label.iloc[:, 1].map(lambda x: None if x == 8 else x)
df_label.iloc[:, 2] = df_label.iloc[:, 2].map(lambda x: None if x == 8 else x)

In [17]:
df_label.head()

,あなたは普段，どのような遊びをよくされていますか？次のジャンルのうち，最も当てはまるものを1つ選択してください(必須)．,あなたは普段，どのような遊びをよくされていますか？次のジャンルのうち，2番目に当てはまるものを1つ選択してください(任意)．,あなたは普段，どのような遊びをよくされていますか？次のジャンルのうち，3番目に当てはまるものを1つ選択してください(任意)．,その他，普段よく遊ばれるジャンルがあれば，当てはまるものを複数選択してください．
0,1,3.0,0.0,None
1,7,3.0,6.0,[5]
2,6,5.0,2.0,None
3,3,6.0,4.0,"[1, 5, 7]"
4,1,0.0,3.0,None

In [24]:
def map_calc_weight(row):
    weight = np.array([1.0, 0.7, 0.4, 0.1])
    vector = np.zeros(len(df_genre) - 1).astype(np.float64)
    
    # 第1~3希望まで重みを計算
    for i, x in enumerate(row[:3]):
        if not np.isnan(x):
            vector[int(x)] = weight[i]
    
    # 第4希望の重みを計算
    if row[3] is not None:
        for x in row[3]:
            vector[int(x)] = weight[-1]
    
    return vector / sum(vector)

df_label.apply(map_calc_weight, axis=1)

0     [0.19047619047619052, 0.4761904761904763, 0.0,...
1     [0.0, 0.0, 0.0, 0.3181818181818181, 0.0, 0.045...
2     [0.0, 0.0, 0.19047619047619047, 0.0, 0.0, 0.33...
3     [0.0, 0.04166666666666667, 0.0, 0.416666666666...
4     [0.3333333333333333, 0.47619047619047616, 0.0,...
5     [0.0, 0.045454545454545456, 0.0, 0.18181818181...
6     [0.0, 0.4347826086956521, 0.3043478260869565, ...
7              [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
8     [0.0, 0.0, 0.0, 0.0, 0.0, 0.28571428571428575,...
9     [0.041666666666666664, 0.16666666666666666, 0....
10    [0.19047619047619052, 0.4761904761904763, 0.0,...
11    [0.0, 0.0, 0.0, 0.4761904761904763, 0.0, 0.190...
12    [0.0, 0.3333333333333333, 0.0, 0.0, 0.0, 0.476...
13    [0.0, 0.47619047619047616, 0.3333333333333333,...
14    [0.0, 0.18181818181818182, 0.0, 0.0, 0.0, 0.04...
15    [0.0, 0.3333333333333333, 0.19047619047619047,...
16    [0.45454545454545453, 0.0, 0.3181818181818181,...
17    [0.0, 0.19047619047619052, 0.0, 0.0, 0.0, 0.0,...
18    [0.04166666666666667, 0.0, 0.04166666666666667...
19    [0.0, 0.0, 0.3333333333333333, 0.1904761904761...
20    [0.0, 0.0, 0.0, 0.6363636363636362, 0.0, 0.0, ...
21    [0.0, 0.043478260869565216, 0.0, 0.17391304347...
22             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
23    [0.0, 0.47619047619047616, 0.0, 0.333333333333...
24    [0.038461538461538464, 0.038461538461538464, 0...
25    [0.0, 0.19047619047619047, 0.0, 0.0, 0.0, 0.33...
26    [0.19047619047619047, 0.3333333333333333, 0.0,...
27    [0.0, 0.0, 0.0, 0.4761904761904763, 0.19047619...
28    [0.0, 0.3181818181818181, 0.045454545454545456...
29    [0.0, 0.0, 0.17391304347826086, 0.043478260869...
30    [0.0, 0.0, 0.0, 0.0, 0.0, 0.5882352941176471, ...
31    [0.0, 0.0, 0.0, 0.0, 0.0, 0.47619047619047616,...
32             [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
33    [0.0, 0.16666666666666666, 0.0, 0.416666666666...
34    [0.0, 0.3043478260869565, 0.17391304347826086,...
35    [0.0, 0.0, 0.45454545454545453, 0.0, 0.1818181...
36    [0.0, 0.47619047619047616, 0.0, 0.333333333333...
37             [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
38    [0.0, 0.4761904761904763, 0.19047619047619052,...
39    [0.0, 0.0, 0.0, 0.4761904761904763, 0.19047619...
40    [0.0, 0.3333333333333333, 0.47619047619047616,...
41    [0.0, 0.0, 0.47619047619047616, 0.333333333333...
dtype: object

In [18]:
# CSV出力
df_csv_weight = df_input.copy()
df_csv_weight['label'] = df_label.apply(map_calc_weight, axis=1)
df_csv_weight.to_csv('/home/res/datasets/static-info_data_weight.csv', index=False)

df_csv_weight

,上記で選択した遊び(普段よくする遊び)を行うときは，1日でお金を平均で幾らほど使われますか？,上記で選択した遊び(普段よくする遊び)を行うときは，自然に囲まれた中で遊びたい気分のときが多いですか？それとも街や駅前に出て遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，エキサイティングな遊びをしたい気分のときが多いですか？それとも，ゆったりのんびり遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，遠出したい気分のときが多いですか？それとも近場で遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，色々な場所を転々としたい気分のときが多いですか？それとも1か所にとどまって遊びたい気分の時が多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，室内で遊びたい気分のときが多いですか？それとも室外で遊びたい気分のときが多いですか？（%の値は～したいという気持ちの度合いです）,上記で選択した遊び(普段よくする遊び)を行うときは，何人の友達と遊びに行くことが多いですか？平均してお答えください．,上記で選択した遊び(普段よくする遊び)を行うときは，人(友達など)とどのくらい会話をしますか？（%の値は～したいという気持ちの度合いです）,label
0,3,3,2,3,4,3,2,4,"[0.4, 1.0, 0.0, 0.7, 0.0, 0.0, 0.0, 0.0]"
1,3,1,1,3,3,4,1,3,"[0.0, 0.0, 0.0, 0.7, 0.0, 0.1, 0.4, 1.0]"
2,5,3,3,1,4,5,1,5,"[0.0, 0.0, 0.4, 0.0, 0.0, 0.7, 1.0, 0.0]"
3,1,2,2,3,3,3,1,3,"[0.0, 0.1, 0.0, 1.0, 0.4, 0.1, 0.7, 0.1]"
4,1,4,2,2,3,3,1,4,"[0.7, 1.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0]"
5,1,3,3,2,3,3,1,3,"[0.0, 0.1, 0.0, 0.4, 0.0, 0.7, 1.0, 0.0]"
6,0,3,2,2,5,1,0,3,"[0.0, 1.0, 0.7, 0.1, 0.0, 0.1, 0.4, 0.0]"
7,0,3,1,1,1,1,2,3,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]"
8,3,4,5,3,4,1,1,3,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 1.0]"
9,5,3,3,4,4,4,3,5,"[0.1, 0.4, 0.0, 0.7, 0.0, 1.0, 0.1, 0.1]"
10,1,3,1,0,1,0,3,3,"[0.4, 1.0, 0.0, 0.0, 0.0, 0.7, 0.0, 0.0]"
11,3,4,5,5,3,4,5,5,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.4, 0.7, 0.0]"
12,2,3,2,1,2,1,1,2,"[0.0, 0.7, 0.0, 0.0, 0.0, 1.0, 0.0, 0.4]"
13,1,4,2,1,2,1,3,4,"[0.0, 1.0, 0.7, 0.0, 0.0, 0.4, 0.0, 0.0]"
14,2,4,4,3,4,1,1,3,"[0.0, 0.4, 0.0, 0.0, 0.0, 0.1, 0.7, 1.0]"
15,1,2,4,2,3,3,0,0,"[0.0, 0.7, 0.4, 0.0, 0.0, 0.0, 0.0, 1.0]"
16,1,1,4,2,2,4,2,4,"[1.0, 0.0, 0.7, 0.4, 0.0, 0.0, 0.0, 0.1]"
17,0,3,1,1,4,4,1,3,"[0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 1.0, 0.7]"
18,1,3,3,3,3,2,2,3,"[0.1, 0.0, 0.1, 1.0, 0.1, 0.7, 0.0, 0.4]"
19,2,3,2,2,4,2,3,4,"[0.0, 0.0, 0.7, 0.4, 0.0, 1.0, 0.0, 0.0]"
20,0,4,4,3,2,1,0,0,"[0.0, 0.0, 0.0, 0.7, 0.0, 0.0, 0.0, 0.4]"
21,1,4,3,2,3,3,1,4,"[0.0, 0.1, 0.0, 0.4, 0.0, 1.0, 0.7, 0.1]"
22,0,3,2,2,4,2,0,0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]"
23,1,2,2,2,3,2,0,0,"[0.0, 1.0, 0.0, 0.7, 0.0, 0.0, 0.4, 0.0]"
24,2,2,4,4,3,4,1,4,"[0.1, 0.1, 1.0, 0.7, 0.1, 0.4, 0.1, 0.1]"
25,3,4,2,2,2,2,0,3,"[0.0, 0.4, 0.0, 0.0, 0.0, 0.7, 0.0, 1.0]"
26,1,1,5,4,2,2,2,4,"[0.4, 0.7, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]"
27,2,1,1,3,3,4,1,4,"[0.0, 0.0, 0.0, 1.0, 0.4, 0.0, 0.7, 0.0]"
28,3,3,3,4,3,3,2,3,"[0.0, 0.7, 0.1, 0.4, 0.0, 1.0, 0.0, 0.0]"
29,3,3,2,1,4,2,1,5,"[0.0, 0.0, 0.4, 0.1, 0.0, 1.0, 0.7, 0.1]"
30,2,2,1,2,2,2,1,3,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.7]"
31,1,4,2,1,2,1,1,3,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.7, 0.4]"
32,1,2,0,1,1,0,5,3,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]"
33,3,3,4,4,3,4,1,4,"[0.0, 0.4, 0.0, 1.0, 0.1, 0.7, 0.1, 0.1]"
34,2,3,2,2,3,2,2,2,"[0.0, 0.7, 0.4, 0.1, 0.0, 0.1, 1.0, 0.0]"
35,3,2,4,4,5,5,1,4,"[0.0, 0.0, 1.0, 0.0, 0.4, 0.1, 0.7, 0.0]"
36,1,1,2,3,1,2,1,3,"[0.0, 1.0, 0.0, 0.7, 0.0, 0.0, 0.4, 0.0]"
37,1,0,5,2,3,5,1,5,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
38,3,3,2,2,4,1,3,4,"[0.0, 1.0, 0.4, 0.0, 0.0, 0.7, 0.0, 0.0]"
39,0,2,1,3,3,3,2,3,"[0.0, 0.0, 0.0, 1.0, 0.4, 0.0, 0.7, 0.0]"
40,1,2,3,2,2,3,5,3,"[0.0, 0.7, 1.0, 0.0, 0.0, 0.4, 0.0, 0.0]"
41,0,2,1,2,4,3,0,2,"[0.0, 0.0, 1.0, 0.7, 0.0, 0.0, 0.0, 0.4]"